services:
  api:
    container_name: api
    image: api:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
  client: 
    container_name: client
    build: ./client
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    ports:
      - 3000:5173
        
volumes:
  node_modules:
    name: node_modules
